
version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    restart: unless-stopped
    # When you add a backend service, uncomment the following:
    # depends_on:
    #   - backend
    networks:
      - app-network

  # Uncomment this when you're ready to add a backend
  # backend:
  #   build:
  #     context: ./backend
  #     dockerfile: Dockerfile
  #   environment:
  #     - MONGO_URI=mongodb://mongo:27017/chat_app
  #   depends_on:
  #     - mongo
  #   networks:
  #     - app-network

  # mongo:
  #   image: mongo:latest
  #   volumes:
  #     - mongo-data:/data/db
  #   networks:
  #     - app-network

networks:
  app-network:
    driver: bridge

# volumes:
#   mongo-data:
